version: '3.8'

services:
  app-notification:
    build: 
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
      target: development
    command: npm run start:dev notification-service
    env_file:
      - ./apps/notification-service/.env

  agragator_db:
    image: postgres:13
    ports:
        - 5432:5432
    env_file:
      - .env
    hostname: agragator_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  
  redis:
    image: redis:6.0.12-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 6379:6379
    hostname: agri-redis
    restart: always

  redis-commander:
    container_name: redis-web
    hostname: redis-web
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_USER=agri_admin
      - HTTP_PASSWORD=agri_admin
    ports:
      - "8089:8089"

