version: '3.8'

services:  
  redis:
    image: redis:6.0.12-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 6379:6379
    hostname: agri-redis
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_USER=agri_admin
      - HTTP_PASSWORD=agri_admin
    ports:
      - "8081:8081"

